---
name: Posy-Plugin-EditInfo
version: 0.03
author:
  - Kathryn Andersen
abstract: Posy plugin to edit supplementary entry information.
license: perl
requires:
  Posy: 0.97
  Posy::Plugin::Info: 0.03
build_requires:
  Test::More: 0
provides:
  Posy::Plugin::EditInfo:
    file: lib/Posy/Plugin/EditInfo.pm
    version: 0.03
generated_by: Module::Build version 0.2611
